name: build

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"

    - name: Print release version
      run: |
        echo $RELEASE_VERSION

    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: docker build release
      run: |
        docker build . -f ./Dockerfile -t haniffalab/adifa:$RELEASE_VERSION

    - name: docker push release
      run: |
        docker push haniffalab/adifa:$RELEASE_VERSION