name: docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: docker build
      if: $RELEASE_VERSION == 'main'  
      run: |
        docker build . -f ./Dockerfile -t haniffalab/adifa:latest
      if: $RELEASE_VERSION != 'main'  
      run: |
        docker build . -f ./Dockerfile -t haniffalab/adifa:$RELEASE_VERSION

    - name: docker push
      if: $RELEASE_VERSION == 'main'  
      run: |
        docker push haniffalab/adifa:latest
      if: $RELEASE_VERSION != 'main'  
      run: |
        docker push haniffalab/adifa:$RELEASE_VERSION
        